branches:
  only:
  - master

language: node_js
node_js:
  - 12

addons:
  chrome: stable # make sure you have Chrome available

cache:
  yarn: true

sudo: false

os:
  - linux

before_script:
  - yarn

before_install:
  - yarn global add @lhci/cli@0.3.x

script:
  - yarn lint
  - yarn test

after_success:
  - lhci autorun
  - yarn deploy
